TaskManagementSystem.Web/Controllers/AdminController.cs
using System.Drawing;
using AspNetCoreGeneratedDocument;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using OfficeOpenXml.Style;
using OfficeOpenXml;
using TaskManagementSystem.Common.BusinessEntities;
using TaskManagementSystem.Common.Utility;
using TaskManagementSystem.Provider.IProvider;
using TaskManagementSystem.Web.Models;
using Microsoft.EntityFrameworkCore;

namespace TaskManagementSystem.Web.Controllers
{
    public class AdminController : BaseController
    {
        IAdminProvider _adminProvider;
        public AdminController(ISessionManager sessionManager, ICommonProvider commonProvider, IAdminProvider adminProvider) : base(sessionManager, commonProvider)
        {
            _adminProvider = adminProvider;
        }

        public IActionResult Index()
        {
            TempData["title"] = "Employee";
            return View();
        }
        [HttpPost]
        public JsonResult GetList()
        {
            return Json(_adminProvider.HiteshTaskUserMasterList(GetPagingRequestModel(), GetSessionProviderParameters()));
        }

        [HttpGet]
        public PartialViewResult _AddEmployee(string id)
        {
            TaskViewModel model = new TaskViewModel();
            if (!id.IsNullOrEmpty())
            {
                model.HiteshTaskUserMasterModel = _adminProvider.GetEmployeeById(_commonProvider.UnProtect(id));
            }

            return PartialView(model);
        }


        [HttpGet]
        public PartialViewResult _UploadExcel()
        {
            TaskViewModel ViewModel=new TaskViewModel();
            // model.HiteshTaskDocumentSaveModel.ProjectId = _commonProvider.UnProtect(id);
            return PartialView(ViewModel);
        }

        [HttpPost]
        public IActionResult SaveEmployee(TaskViewModel model)
        {
            var session = GetSessionProviderParameters();
            ResponseModel responseModel = new ResponseModel();
            responseModel = _adminProvider.SaveEmployee(model.HiteshTaskUserMasterModel, session);
            return Json(responseModel);
        }


        [HttpPost]
        public JsonResult DeleteEmployee(string id)
        {
            ResponseModel user = new ResponseModel();
            user = _adminProvider.DeleteEmployee(_commonProvider.UnProtect(id));

            if (user.IsSuccess)
            {
                user.IsSuccess = true;
                user.Message = "Delete successfull";
            }

            return Json(user);

        }



        [HttpPost]
        public IActionResult UploadExcel(IFormFile excelFile)
        {
               

            var successList = new List<HiteshTaskUserMasterModel>();
            var errorList = new List<HiteshTaskUserMasterModel>();
            TaskViewModel ViewModel = new TaskViewModel();
            HiteshTaskUserMasterModel model=new HiteshTaskUserMasterModel();
            int success = 0;
            int error = 0;
            using (var stream = new MemoryStream())
            {
                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
                 excelFile.CopyToAsync(stream);
                using (var package = new ExcelPackage(stream))
                {
                    var worksheet = package.Workbook.Worksheets[0];
                    // int rowCount = worksheet.Dimension.Rows;
                    var validRowIndices = new List<int>();
                    int totalRows = worksheet.Dimension.End.Row;
                    int totalColumns = worksheet.Dimension.End.Column;

                    // Identify non-empty rows
                    for (int row = 2; row <= totalRows; row++) // Assuming row 1 is header
                    {
                        bool isRowEmpty = true;

                        for (int col = 1; col <= totalColumns; col++)
                        {
                            var cellValue = worksheet.Cells[row, col].Text;

                            if (!string.IsNullOrWhiteSpace(cellValue))
                            {
                                isRowEmpty = false;
                                break;
                            }
                        }

                        if (!isRowEmpty)
                        {
                            validRowIndices.Add(row);
                        }
                    }

                    // Process only non-empty rows
                    foreach (var row in validRowIndices)
                    {
                         model = new HiteshTaskUserMasterModel
                        {
                            FullName = worksheet.Cells[row, 1].Text,
                            Email = worksheet.Cells[row, 2].Text,
                            Password = worksheet.Cells[row, 3].Text
                        };

                        var validationMessages = new List<string>();

                        if (string.IsNullOrWhiteSpace(model.FullName))
                            validationMessages.Add("FullName is required.");

                        if (string.IsNullOrWhiteSpace(model.Email))
                            validationMessages.Add("Email is required.");

                        if (string.IsNullOrWhiteSpace(model.Password))
                            validationMessages.Add("Password is required.");
                        else if (model.Password.Length < 6)
                            validationMessages.Add("Password must be at least 6 characters.");

                        var isEmailExists = _adminProvider.CheckEmail(model.Email);
                        if (isEmailExists.IsSuccess)
                        {
                            validationMessages.Add("Email already exists.");
                        }

                        if (validationMessages.Any())
                        {
                            model.Message = string.Join(" ", validationMessages);
                            errorList.Add(model);
                            error++;
                        }
                        else
                        {
                            success++;
                            _adminProvider.SaveEmployee(model, GetSessionProviderParameters());
                        }
                    }


                }

                // Save error list to Excel
                if (errorList.Any())
                {
                    var errorFilePath = Path.Combine("wwwroot/Documents", "ErrorData.xlsx");
                    using (var package = new ExcelPackage())
                    {
                        var ws = package.Workbook.Worksheets.Add("Errors");
                        ws.Cells[1, 1].Value = "Exception Message";
                        ws.Cells[1, 2].Value = "FullName";
                        ws.Cells[1, 3].Value = "Email";
                        ws.Cells[1, 4].Value = "Password";
                        

                        for (int i = 0; i < errorList.Count; i++)
                        {
                            ws.Cells[i + 2, 1].Value = errorList[i].Message ?? "";
                            ws.Cells[i + 2, 2].Value = errorList[i].FullName ?? null;
                            ws.Cells[i + 2, 3].Value = errorList[i].Email;
                            ws.Cells[i + 2, 4].Value = errorList[i].Password;
                           
                        }
                        ws.Cells.AutoFitColumns();
                        package.SaveAs(new FileInfo(errorFilePath));
                    }
                }

                // Send result back to view
                ViewModel.isSuccess = true;
                ViewModel.success = success;
                ViewModel.errorcount = error;
                ViewModel.total = success + error;
                //TempData["Total"] = successList.Count + errorList.Count;
                //TempData["Success"] = successList.Count;
                //TempData["Error"] = errorList.Count;
                //TempData["HasErrorFile"] = errorList.Any();

                

            }

            return Json(ViewModel);
        }
    }
}

TaskManagementSystem.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using TaskManagementSystem.Common.BusinessEntities;
using TaskManagementSystem.Common.Utility;
using TaskManagementSystem.Provider.IProvider;
using TaskManagementSystem.Provider.Provider;
using TaskManagementSystem.Web.Models;

namespace TaskManagementSystem.Web.Controllers
{
    public class UserController : BaseController
    {
        IUserProvider _userProvider;
        public UserController(ISessionManager sessionManager, ICommonProvider commonProvider, IUserProvider userProvider) : base(sessionManager, commonProvider)
        {
            _userProvider = userProvider;
        }

        [HttpGet]
        public IActionResult Index()
        {
            TempData["title"] = "Project";
            TaskViewModel taskViewModel = new TaskViewModel();
            return View(taskViewModel);
        }
        [HttpPost]
        public JsonResult GetList()
        {
            return Json(_userProvider.HiteshTaskProjectList(GetPagingRequestModel(),GetSessionProviderParameters()));
        }

        [HttpGet]
        public IActionResult Task()
        {
            TempData["title"] = "Task";
            TaskViewModel taskViewModel = new TaskViewModel();
            return View(taskViewModel);
        }

        [HttpPost]
        public JsonResult GetTaskList()
        {
            return Json(_userProvider.HiteshTaskList(GetPagingRequestModel(),GetSessionProviderParameters()));
        }


        [HttpGet]
        public IActionResult Calender()
        {
            TempData["title"] = "Calender";
            TaskViewModel taskViewModel = new TaskViewModel();
            return View(taskViewModel);
        }

        [HttpPost]
        public JsonResult GetToDoCount(int month, int year)
        {
            var startDate = new DateTime(year, month, 1);
            var endDate = startDate.AddMonths(1).AddDays(-1);

            TaskViewModel taskViewModel = new TaskViewModel();
            taskViewModel.HiteshAssignTaskModelList=_userProvider.GetToDoCount(startDate, endDate,GetSessionProviderParameters());
             
            return Json(taskViewModel.HiteshAssignTaskModelList);
        }



        [HttpGet]
        public PartialViewResult _GetTaskByDate(string date)
        {
            TaskViewModel model = new TaskViewModel();
            if (date !=null)
            {

                model.HiteshTaskAssignTaskModel.SlotDate = date;
                model.HiteshAssignTaskModelList = _userProvider.GetDateData(date,GetSessionProviderParameters());
                model.HiteshTaskAssignTaskModel.roleid = _sessionManager.RoleId;

            }

            return PartialView(model);
        }


        [HttpPost]
        public JsonResult StatusChange(string Encid, int id)
        {

            ResponseModel responseModel = new ResponseModel();
            HiteshTaskAssignTaskModel model = new HiteshTaskAssignTaskModel();
            int UserId = _commonProvider.UnProtect(Encid);

            var data = _userProvider.StatusChange(UserId, id,GetSessionProviderParameters());
            return Json(new { isSuccess = true, status = id });




        }





        [HttpGet]
        public PartialViewResult _ShowMessage(int id)
        {
            TaskViewModel model = new TaskViewModel();
            if (id>0)
            {
                
                model.HIteshTaskMessageModel.SendId = _sessionManager.UserId;
                model.HIteshTaskMessageModel.ReceiveId = id;
                model.HiteshTaskUserMasterModel = _userProvider.GetUserById(id);
               
                
                model.HIteshTaskMessageModel.AllMessage=_userProvider.GetMessage(_sessionManager.UserId,id);
                
            }

            return PartialView(model);
        }

        [HttpPost]
        public JsonResult MsgSave(TaskViewModel model)
        {
            HIteshTaskMessageModel user = new HIteshTaskMessageModel();

            user = _userProvider.SaveMessage(model.HIteshTaskMessageModel);

            if (user.IsSuccess)
            {
                
                user.IsSuccess = true;
                user.Message = "save successfull";
            }

            return Json(new
            {
                isSuccess = user.IsSuccess,
                recId = user.ReceiveId,
               
                message = "save successful"
            });

        }


    }
}

TaskManagementSystem.Web/Views/Shared/Components/MenuView/Default.cshtml
@model TaskManagementSystem.Web.Models.TaskViewModel 

<aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <!-- User Profile-->
                        <li>
                            <!-- User Profile-->
                            @* <div class="user-profile d-flex no-block dropdown mt-3"> *@
                            @*     <div class="user-pic"><img src="../../assets/images/users/1.jpg" alt="users" class="rounded-circle" width="40" /></div> *@
                            @*     <div class="user-content hide-menu ml-2"> *@
                            @*         <a href="javascript:void(0)" class="" id="Userdd" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> *@
                            @*             <h5 class="mb-0 user-name font-medium">Steave Jobs <i class="fa fa-angle-down"></i></h5> *@
                            @*             <span class="op-5 user-email">varun@gmail.com</span> *@
                            @*         </a> *@
                            @*         <div class="dropdown-menu dropdown-menu-right" aria-labelledby="Userdd"> *@
                            @*             <a class="dropdown-item" href="javascript:void(0)"><i class="ti-user mr-1 ml-1"></i> My Profile</a> *@
                            @*             <a class="dropdown-item" href="javascript:void(0)"><i class="ti-wallet mr-1 ml-1"></i> My Balance</a> *@
                            @*             <a class="dropdown-item" href="javascript:void(0)"><i class="ti-email mr-1 ml-1"></i> Inbox</a> *@
                            @*             <div class="dropdown-divider"></div> *@
                            @*             <a class="dropdown-item" href="javascript:void(0)"><i class="ti-settings mr-1 ml-1"></i> Account Setting</a> *@
                            @*             <div class="dropdown-divider"></div> *@
                            @*             <a class="dropdown-item" href="javascript:void(0)"><i class="fa fa-power-off mr-1 ml-1"></i> Logout</a> *@
                            @*         </div> *@
                            @*     </div> *@
                            @* </div> *@
                            <!-- End User Profile-->
                        </li>
                        <!-- User Profile-->
                        @* <li class="nav-small-cap"><i class="mdi mdi-dots-horizontal"></i> <span class="hide-menu">Menu</span></li> *@

                        @{


                    <li class="sidebar-item">


                        <a class="sidebar-link  waves-effect waves-dark" aria-expanded="false" asp-action="SHowChart" asp-controller="Dashboard"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">DashBoard </span></a>

                    </li>

                    if (@Model.RoleId==1)
                    {

                        

                        <li class="sidebar-item">


                            <a class="sidebar-link  waves-effect waves-dark" aria-expanded="false" asp-action="Index" asp-controller="Admin"><i class="mdi mdi-solid fa-user"></i><span class="hide-menu">Employee </span></a>

                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark" aria-expanded="false" asp-action="Index" asp-controller="Project" ><i class="mdi mdi-tune-vertical"></i><span class="hide-menu">Project </span></a>

                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link  waves-effect waves-dark" aria-expanded="false" asp-action="Index" asp-controller="Task" ><i class="fa-solid fa-list-check"></i><span class="hide-menu">Task </span></a>

                        </li>
                       
                    }
                     else{
                      

                        <li class="sidebar-item">
                            <a class="sidebar-link waves-effect waves-dark" aria-expanded="false" asp-action="Index" asp-controller="User" ><i class="mdi mdi-tune-vertical"></i><span class="hide-menu">Project </span></a>

                        </li> 
                        <li class="sidebar-item">
                            <a class="sidebar-link  waves-effect waves-dark" aria-expanded="false" asp-action="Task" asp-controller="User" ><i class="fa-solid fa-list-check"></i><span class="hide-menu">Task </span></a>

                        </li>

                        
                     } 

                 }
                <li class="sidebar-item">
                    <a class="sidebar-link  waves-effect waves-dark" aria-expanded="false" asp-action="Calender" asp-controller="User"><i class="fa-solid fa-calendar-days"></i><span class="hide-menu">Calender </span></a>

                </li>







                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>



<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-breadcrumb">
        <div class="row">
            <div class="col-5 align-self-center">
                <h4 class="page-title" id="dashboard">@TempData["title"] </h4>
                @* <div class="d-flex align-items-center"> *@
                @*     <nav aria-label="breadcrumb"> *@
                @*         <ol class="breadcrumb"> *@
                @*             <li class="breadcrumb-item"><a href="#">Home</a></li> *@
                @*             <li class="breadcrumb-item active" aria-current="page">Library</li> *@
                @*         </ol> *@
                @*     </nav> *@
                @* </div> *@
            </div>
            <div class="col-7 align-self-center">
                @* <div class="d-flex no-block justify-content-end align-items-center"> *@
                @*     <div class="mr-2"> *@
                @*         <div class="lastmonth"></div> *@
                @*     </div> *@
                @*     <div class=""> *@
                @*         <small>LAST MONTH</small> *@
                @*         <h4 class="text-info mb-0 font-medium">$58,256</h4> *@
                @*     </div> *@
                @* </div> *@

                @* <div class="d-flex align-items-center"> *@
                <div class="d-flex no-block justify-content-end align-items-center">
                    <nav aria-label="breadcrumb" class="mr-2">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page" id="main">@TempData["title"] </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
@* <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script> *@
@* <script type="text/javascript"> *@
@*     function updateBreadcrumb(title) { *@
@*         debugger; *@
@*           $("#dashboard").text(title); *@
@*           $("#main").text(title); *@
@*       } *@
@* </script> *@